In [1]:
import numpy as np


In [2]:
np.random.uniform(-1,1,18)

array([-0.25697209, -0.56506957,  0.84390634,  0.21724558,  0.54328956,
       -0.49683564,  0.77299428, -0.22588412, -0.40406352, -0.89976666,
        0.02562606,  0.75575362, -0.36609868,  0.12501063,  0.93832107,
        0.24625981,  0.57724916,  0.24532134])

In [5]:
def rescale(action, min_action, max_action):
    action_new = np.zeros_like(action)
    for i in range(action.shape[0]):
        a = action[i]+1
        ratio = a/2
        new_a = ratio*(max_action[i]-min_action[i])
        action_new[i] = min_action[i] + new_a
    return action_new

In [6]:
new_action = rescale(np.array([-1,0,1]), np.array([-2,-2,-2]), np.array([2,2,2]))

In [7]:
new_action

array([-2,  0,  2])

In [11]:
np.array([[-1,-1,0]]).repeat(6, 0)

array([[-1, -1,  0],
       [-1, -1,  0],
       [-1, -1,  0],
       [-1, -1,  0],
       [-1, -1,  0],
       [-1, -1,  0]])